/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.validation;

import fr.uha.ensisa.project.pan_chabalier.tse.validation.AbstractTSEValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TSEValidator extends AbstractTSEValidator {
}
