/*
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.parser.antlr;

import com.google.inject.Inject;
import fr.uha.ensisa.project.pan_chabalier.tse.parser.antlr.internal.InternalTSEParser;
import fr.uha.ensisa.project.pan_chabalier.tse.services.TSEGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TSEParser extends AbstractAntlrParser {

	@Inject
	private TSEGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTSEParser createParser(XtextTokenStream stream) {
		return new InternalTSEParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TSEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TSEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
