/*
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.ui.tests;

import com.google.inject.Injector;
import fr.uha.ensisa.project.pan_chabalier.ui.internal.Pan_chabalierActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TSEUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Pan_chabalierActivator.getInstance().getInjector("fr.uha.ensisa.project.pan_chabalier.TSE");
	}

}
