/*
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.ui;

import com.google.inject.Injector;
import fr.uha.ensisa.project.pan_chabalier.ui.internal.Pan_chabalierActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TSEExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Pan_chabalierActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Pan_chabalierActivator.getInstance().getInjector(Pan_chabalierActivator.FR_UHA_ENSISA_PROJECT_PAN_CHABALIER_TSE_TSE);
	}
	
}
