/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.ide;

import fr.uha.ensisa.project.pan_chabalier.ide.AbstractTSEIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TSEIdeModule extends AbstractTSEIdeModule {
}
