/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl;

import fr.uha.ensisa.project.pan_chabalier.tse.tSE.EndTransition;
import fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage;
import fr.uha.ensisa.project.pan_chabalier.tse.tSE.Transition;
import fr.uha.ensisa.project.pan_chabalier.tse.tSE.transitionProperties;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.TransitionImpl#getStart <em>Start</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.TransitionImpl#getEnd <em>End</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.TransitionImpl#getProprietyStates <em>Propriety States</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.TransitionImpl#getLabel <em>Label</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.TransitionImpl#getInit <em>Init</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TransitionImpl extends MinimalEObjectImpl.Container implements Transition
{
  /**
   * The cached value of the '{@link #getStart() <em>Start</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStart()
   * @generated
   * @ordered
   */
  protected EList<String> start;

  /**
   * The cached value of the '{@link #getEnd() <em>End</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected EList<EndTransition> end;

  /**
   * The cached value of the '{@link #getProprietyStates() <em>Propriety States</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProprietyStates()
   * @generated
   * @ordered
   */
  protected EList<transitionProperties> proprietyStates;

  /**
   * The default value of the '{@link #getLabel() <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabel()
   * @generated
   * @ordered
   */
  protected static final String LABEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLabel() <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabel()
   * @generated
   * @ordered
   */
  protected String label = LABEL_EDEFAULT;

  /**
   * The cached value of the '{@link #getInit() <em>Init</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit()
   * @generated
   * @ordered
   */
  protected EList<String> init;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TSEPackage.Literals.TRANSITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getStart()
  {
    if (start == null)
    {
      start = new EDataTypeEList<String>(String.class, this, TSEPackage.TRANSITION__START);
    }
    return start;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<EndTransition> getEnd()
  {
    if (end == null)
    {
      end = new EObjectContainmentEList<EndTransition>(EndTransition.class, this, TSEPackage.TRANSITION__END);
    }
    return end;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<transitionProperties> getProprietyStates()
  {
    if (proprietyStates == null)
    {
      proprietyStates = new EObjectContainmentEList<transitionProperties>(transitionProperties.class, this, TSEPackage.TRANSITION__PROPRIETY_STATES);
    }
    return proprietyStates;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLabel()
  {
    return label;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLabel(String newLabel)
  {
    String oldLabel = label;
    label = newLabel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TSEPackage.TRANSITION__LABEL, oldLabel, label));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getInit()
  {
    if (init == null)
    {
      init = new EDataTypeEList<String>(String.class, this, TSEPackage.TRANSITION__INIT);
    }
    return init;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION__END:
        return ((InternalEList<?>)getEnd()).basicRemove(otherEnd, msgs);
      case TSEPackage.TRANSITION__PROPRIETY_STATES:
        return ((InternalEList<?>)getProprietyStates()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION__START:
        return getStart();
      case TSEPackage.TRANSITION__END:
        return getEnd();
      case TSEPackage.TRANSITION__PROPRIETY_STATES:
        return getProprietyStates();
      case TSEPackage.TRANSITION__LABEL:
        return getLabel();
      case TSEPackage.TRANSITION__INIT:
        return getInit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION__START:
        getStart().clear();
        getStart().addAll((Collection<? extends String>)newValue);
        return;
      case TSEPackage.TRANSITION__END:
        getEnd().clear();
        getEnd().addAll((Collection<? extends EndTransition>)newValue);
        return;
      case TSEPackage.TRANSITION__PROPRIETY_STATES:
        getProprietyStates().clear();
        getProprietyStates().addAll((Collection<? extends transitionProperties>)newValue);
        return;
      case TSEPackage.TRANSITION__LABEL:
        setLabel((String)newValue);
        return;
      case TSEPackage.TRANSITION__INIT:
        getInit().clear();
        getInit().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION__START:
        getStart().clear();
        return;
      case TSEPackage.TRANSITION__END:
        getEnd().clear();
        return;
      case TSEPackage.TRANSITION__PROPRIETY_STATES:
        getProprietyStates().clear();
        return;
      case TSEPackage.TRANSITION__LABEL:
        setLabel(LABEL_EDEFAULT);
        return;
      case TSEPackage.TRANSITION__INIT:
        getInit().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION__START:
        return start != null && !start.isEmpty();
      case TSEPackage.TRANSITION__END:
        return end != null && !end.isEmpty();
      case TSEPackage.TRANSITION__PROPRIETY_STATES:
        return proprietyStates != null && !proprietyStates.isEmpty();
      case TSEPackage.TRANSITION__LABEL:
        return LABEL_EDEFAULT == null ? label != null : !LABEL_EDEFAULT.equals(label);
      case TSEPackage.TRANSITION__INIT:
        return init != null && !init.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (start: ");
    result.append(start);
    result.append(", label: ");
    result.append(label);
    result.append(", init: ");
    result.append(init);
    result.append(')');
    return result.toString();
  }

} //TransitionImpl
