/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl;

import fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage;
import fr.uha.ensisa.project.pan_chabalier.tse.tSE.transitionProperties;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>transition Properties</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.transitionPropertiesImpl#getColor <em>Color</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.transitionPropertiesImpl#getThickness <em>Thickness</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.transitionPropertiesImpl#getCurve <em>Curve</em>}</li>
 * </ul>
 *
 * @generated
 */
public class transitionPropertiesImpl extends MinimalEObjectImpl.Container implements transitionProperties
{
  /**
   * The default value of the '{@link #getColor() <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected static final String COLOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getColor() <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected String color = COLOR_EDEFAULT;

  /**
   * The default value of the '{@link #getThickness() <em>Thickness</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThickness()
   * @generated
   * @ordered
   */
  protected static final String THICKNESS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getThickness() <em>Thickness</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThickness()
   * @generated
   * @ordered
   */
  protected String thickness = THICKNESS_EDEFAULT;

  /**
   * The default value of the '{@link #getCurve() <em>Curve</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCurve()
   * @generated
   * @ordered
   */
  protected static final String CURVE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCurve() <em>Curve</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCurve()
   * @generated
   * @ordered
   */
  protected String curve = CURVE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected transitionPropertiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TSEPackage.Literals.TRANSITION_PROPERTIES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getColor()
  {
    return color;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setColor(String newColor)
  {
    String oldColor = color;
    color = newColor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TSEPackage.TRANSITION_PROPERTIES__COLOR, oldColor, color));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getThickness()
  {
    return thickness;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setThickness(String newThickness)
  {
    String oldThickness = thickness;
    thickness = newThickness;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TSEPackage.TRANSITION_PROPERTIES__THICKNESS, oldThickness, thickness));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCurve()
  {
    return curve;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCurve(String newCurve)
  {
    String oldCurve = curve;
    curve = newCurve;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TSEPackage.TRANSITION_PROPERTIES__CURVE, oldCurve, curve));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION_PROPERTIES__COLOR:
        return getColor();
      case TSEPackage.TRANSITION_PROPERTIES__THICKNESS:
        return getThickness();
      case TSEPackage.TRANSITION_PROPERTIES__CURVE:
        return getCurve();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION_PROPERTIES__COLOR:
        setColor((String)newValue);
        return;
      case TSEPackage.TRANSITION_PROPERTIES__THICKNESS:
        setThickness((String)newValue);
        return;
      case TSEPackage.TRANSITION_PROPERTIES__CURVE:
        setCurve((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION_PROPERTIES__COLOR:
        setColor(COLOR_EDEFAULT);
        return;
      case TSEPackage.TRANSITION_PROPERTIES__THICKNESS:
        setThickness(THICKNESS_EDEFAULT);
        return;
      case TSEPackage.TRANSITION_PROPERTIES__CURVE:
        setCurve(CURVE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION_PROPERTIES__COLOR:
        return COLOR_EDEFAULT == null ? color != null : !COLOR_EDEFAULT.equals(color);
      case TSEPackage.TRANSITION_PROPERTIES__THICKNESS:
        return THICKNESS_EDEFAULT == null ? thickness != null : !THICKNESS_EDEFAULT.equals(thickness);
      case TSEPackage.TRANSITION_PROPERTIES__CURVE:
        return CURVE_EDEFAULT == null ? curve != null : !CURVE_EDEFAULT.equals(curve);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (color: ");
    result.append(color);
    result.append(", thickness: ");
    result.append(thickness);
    result.append(", curve: ");
    result.append(curve);
    result.append(')');
    return result.toString();
  }

} //transitionPropertiesImpl
