/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl;

import fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage;
import fr.uha.ensisa.project.pan_chabalier.tse.tSE.transitionProperties;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>transition Properties</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.transitionPropertiesImpl#getColor <em>Color</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.transitionPropertiesImpl#getThickness <em>Thickness</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.impl.transitionPropertiesImpl#getCurve <em>Curve</em>}</li>
 * </ul>
 *
 * @generated
 */
public class transitionPropertiesImpl extends MinimalEObjectImpl.Container implements transitionProperties
{
  /**
   * The cached value of the '{@link #getColor() <em>Color</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected EList<String> color;

  /**
   * The cached value of the '{@link #getThickness() <em>Thickness</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThickness()
   * @generated
   * @ordered
   */
  protected EList<String> thickness;

  /**
   * The cached value of the '{@link #getCurve() <em>Curve</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCurve()
   * @generated
   * @ordered
   */
  protected EList<String> curve;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected transitionPropertiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TSEPackage.Literals.TRANSITION_PROPERTIES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getColor()
  {
    if (color == null)
    {
      color = new EDataTypeEList<String>(String.class, this, TSEPackage.TRANSITION_PROPERTIES__COLOR);
    }
    return color;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getThickness()
  {
    if (thickness == null)
    {
      thickness = new EDataTypeEList<String>(String.class, this, TSEPackage.TRANSITION_PROPERTIES__THICKNESS);
    }
    return thickness;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getCurve()
  {
    if (curve == null)
    {
      curve = new EDataTypeEList<String>(String.class, this, TSEPackage.TRANSITION_PROPERTIES__CURVE);
    }
    return curve;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION_PROPERTIES__COLOR:
        return getColor();
      case TSEPackage.TRANSITION_PROPERTIES__THICKNESS:
        return getThickness();
      case TSEPackage.TRANSITION_PROPERTIES__CURVE:
        return getCurve();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION_PROPERTIES__COLOR:
        getColor().clear();
        getColor().addAll((Collection<? extends String>)newValue);
        return;
      case TSEPackage.TRANSITION_PROPERTIES__THICKNESS:
        getThickness().clear();
        getThickness().addAll((Collection<? extends String>)newValue);
        return;
      case TSEPackage.TRANSITION_PROPERTIES__CURVE:
        getCurve().clear();
        getCurve().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION_PROPERTIES__COLOR:
        getColor().clear();
        return;
      case TSEPackage.TRANSITION_PROPERTIES__THICKNESS:
        getThickness().clear();
        return;
      case TSEPackage.TRANSITION_PROPERTIES__CURVE:
        getCurve().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TSEPackage.TRANSITION_PROPERTIES__COLOR:
        return color != null && !color.isEmpty();
      case TSEPackage.TRANSITION_PROPERTIES__THICKNESS:
        return thickness != null && !thickness.isEmpty();
      case TSEPackage.TRANSITION_PROPERTIES__CURVE:
        return curve != null && !curve.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (color: ");
    result.append(color);
    result.append(", thickness: ");
    result.append(thickness);
    result.append(", curve: ");
    result.append(curve);
    result.append(')');
    return result.toString();
  }

} //transitionPropertiesImpl
