/*
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TSERuntimeModule extends AbstractTSERuntimeModule {
}
