/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.ui;

import fr.uha.ensisa.project.pan_chabalier.ui.AbstractTSEUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TSEUiModule extends AbstractTSEUiModule {
  public TSEUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
