/*
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TSEGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.Model");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Model:
		//	elements+=Element*;
		@Override public ParserRule getRule() { return rule; }
		
		//elements+=Element*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//Element
		public RuleCall getElementsElementParserRuleCall_0() { return cElementsElementParserRuleCall_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cStatesAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cStatesStateParserRuleCall_0_0 = (RuleCall)cStatesAssignment_0.eContents().get(0);
		private final Assignment cTransitionsAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cTransitionsTransitionParserRuleCall_1_0 = (RuleCall)cTransitionsAssignment_1.eContents().get(0);
		
		//Element:
		//	states+=State
		//	| transitions+=Transition;
		@Override public ParserRule getRule() { return rule; }
		
		//states+=State | transitions+=Transition
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//states+=State
		public Assignment getStatesAssignment_0() { return cStatesAssignment_0; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_0_0() { return cStatesStateParserRuleCall_0_0; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_1() { return cTransitionsAssignment_1; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_1_0() { return cTransitionsTransitionParserRuleCall_1_0; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cStatesProprietyAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStatesProprietyStatesPropertiesParserRuleCall_2_0 = (RuleCall)cStatesProprietyAssignment_2.eContents().get(0);
		
		//State:
		//	"state" name+=ID statesPropriety+=StatesProperties*;
		@Override public ParserRule getRule() { return rule; }
		
		//"state" name+=ID statesPropriety+=StatesProperties*
		public Group getGroup() { return cGroup; }
		
		//"state"
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }
		
		//name+=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//statesPropriety+=StatesProperties*
		public Assignment getStatesProprietyAssignment_2() { return cStatesProprietyAssignment_2; }
		
		//StatesProperties
		public RuleCall getStatesProprietyStatesPropertiesParserRuleCall_2_0() { return cStatesProprietyStatesPropertiesParserRuleCall_2_0; }
	}
	public class StatesPropertiesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.StatesProperties");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cColorKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cColorAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cColorCOLORTerminalRuleCall_0_1_0 = (RuleCall)cColorAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cThicknessKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cThicknessAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cThicknessFLOATTerminalRuleCall_1_1_0 = (RuleCall)cThicknessAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cPositionKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPositionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPositionIDTerminalRuleCall_2_1_0 = (RuleCall)cPositionAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final RuleCall cDEFAULTTerminalRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final Assignment cPositionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPositionIDTerminalRuleCall_3_1_0 = (RuleCall)cPositionAssignment_3_1.eContents().get(0);
		
		//StatesProperties:
		//	"color" color+=COLOR
		//	| "thickness" thickness+=FLOAT
		//	| "position" position+=ID
		//	| DEFAULT position+=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//"color" color+=COLOR | "thickness" thickness+=FLOAT | "position" position+=ID | DEFAULT position+=ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"color" color+=COLOR
		public Group getGroup_0() { return cGroup_0; }
		
		//"color"
		public Keyword getColorKeyword_0_0() { return cColorKeyword_0_0; }
		
		//color+=COLOR
		public Assignment getColorAssignment_0_1() { return cColorAssignment_0_1; }
		
		//COLOR
		public RuleCall getColorCOLORTerminalRuleCall_0_1_0() { return cColorCOLORTerminalRuleCall_0_1_0; }
		
		//"thickness" thickness+=FLOAT
		public Group getGroup_1() { return cGroup_1; }
		
		//"thickness"
		public Keyword getThicknessKeyword_1_0() { return cThicknessKeyword_1_0; }
		
		//thickness+=FLOAT
		public Assignment getThicknessAssignment_1_1() { return cThicknessAssignment_1_1; }
		
		//FLOAT
		public RuleCall getThicknessFLOATTerminalRuleCall_1_1_0() { return cThicknessFLOATTerminalRuleCall_1_1_0; }
		
		//"position" position+=ID
		public Group getGroup_2() { return cGroup_2; }
		
		//"position"
		public Keyword getPositionKeyword_2_0() { return cPositionKeyword_2_0; }
		
		//position+=ID
		public Assignment getPositionAssignment_2_1() { return cPositionAssignment_2_1; }
		
		//ID
		public RuleCall getPositionIDTerminalRuleCall_2_1_0() { return cPositionIDTerminalRuleCall_2_1_0; }
		
		//DEFAULT position+=ID
		public Group getGroup_3() { return cGroup_3; }
		
		//DEFAULT
		public RuleCall getDEFAULTTerminalRuleCall_3_0() { return cDEFAULTTerminalRuleCall_3_0; }
		
		//position+=ID
		public Assignment getPositionAssignment_3_1() { return cPositionAssignment_3_1; }
		
		//ID
		public RuleCall getPositionIDTerminalRuleCall_3_1_0() { return cPositionIDTerminalRuleCall_3_1_0; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.Transition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cTransitionKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cStartAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cStartIDTerminalRuleCall_0_1_0 = (RuleCall)cStartAssignment_0_1.eContents().get(0);
		private final Assignment cEndAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cEndEndTransitionParserRuleCall_0_2_0 = (RuleCall)cEndAssignment_0_2.eContents().get(0);
		private final Assignment cProprietyStatesAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cProprietyStatesTransitionPropertiesParserRuleCall_0_3_0 = (RuleCall)cProprietyStatesAssignment_0_3.eContents().get(0);
		private final Assignment cLabelAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final RuleCall cLabelLabelParserRuleCall_0_4_0 = (RuleCall)cLabelAssignment_0_4.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cInitialTransitionKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cInitAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cInitIDTerminalRuleCall_1_1_0 = (RuleCall)cInitAssignment_1_1.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		
		//Transition:
		//	"transition" start+=ID end+=EndTransition proprietyStates+=transitionProperties* label=Label?
		//	| "initialTransition" init+=ID INT;
		@Override public ParserRule getRule() { return rule; }
		
		//"transition" start+=ID end+=EndTransition proprietyStates+=transitionProperties* label=Label? | "initialTransition"
		//init+=ID INT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"transition" start+=ID end+=EndTransition proprietyStates+=transitionProperties* label=Label?
		public Group getGroup_0() { return cGroup_0; }
		
		//"transition"
		public Keyword getTransitionKeyword_0_0() { return cTransitionKeyword_0_0; }
		
		//start+=ID
		public Assignment getStartAssignment_0_1() { return cStartAssignment_0_1; }
		
		//ID
		public RuleCall getStartIDTerminalRuleCall_0_1_0() { return cStartIDTerminalRuleCall_0_1_0; }
		
		//end+=EndTransition
		public Assignment getEndAssignment_0_2() { return cEndAssignment_0_2; }
		
		//EndTransition
		public RuleCall getEndEndTransitionParserRuleCall_0_2_0() { return cEndEndTransitionParserRuleCall_0_2_0; }
		
		//proprietyStates+=transitionProperties*
		public Assignment getProprietyStatesAssignment_0_3() { return cProprietyStatesAssignment_0_3; }
		
		//transitionProperties
		public RuleCall getProprietyStatesTransitionPropertiesParserRuleCall_0_3_0() { return cProprietyStatesTransitionPropertiesParserRuleCall_0_3_0; }
		
		//label=Label?
		public Assignment getLabelAssignment_0_4() { return cLabelAssignment_0_4; }
		
		//Label
		public RuleCall getLabelLabelParserRuleCall_0_4_0() { return cLabelLabelParserRuleCall_0_4_0; }
		
		//"initialTransition" init+=ID INT
		public Group getGroup_1() { return cGroup_1; }
		
		//"initialTransition"
		public Keyword getInitialTransitionKeyword_1_0() { return cInitialTransitionKeyword_1_0; }
		
		//init+=ID
		public Assignment getInitAssignment_1_1() { return cInitAssignment_1_1; }
		
		//ID
		public RuleCall getInitIDTerminalRuleCall_1_1_0() { return cInitIDTerminalRuleCall_1_1_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_2() { return cINTTerminalRuleCall_1_2; }
	}
	public class LabelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.Label");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLabelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Label:
		//	"label" INT;
		@Override public ParserRule getRule() { return rule; }
		
		//"label" INT
		public Group getGroup() { return cGroup; }
		
		//"label"
		public Keyword getLabelKeyword_0() { return cLabelKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EndTransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.EndTransition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cEndAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cEndIDTerminalRuleCall_0_1_0 = (RuleCall)cEndAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cReflexiveKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cEndAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Keyword cEndReflexiveKeyword_1_1_0 = (Keyword)cEndAssignment_1_1.eContents().get(0);
		
		//EndTransition:
		//	"->" end+=ID
		//	| "reflexive" end+="reflexive";
		@Override public ParserRule getRule() { return rule; }
		
		//"->" end+=ID | "reflexive" end+="reflexive"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"->" end+=ID
		public Group getGroup_0() { return cGroup_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_0_0() { return cHyphenMinusGreaterThanSignKeyword_0_0; }
		
		//end+=ID
		public Assignment getEndAssignment_0_1() { return cEndAssignment_0_1; }
		
		//ID
		public RuleCall getEndIDTerminalRuleCall_0_1_0() { return cEndIDTerminalRuleCall_0_1_0; }
		
		//"reflexive" end+="reflexive"
		public Group getGroup_1() { return cGroup_1; }
		
		//"reflexive"
		public Keyword getReflexiveKeyword_1_0() { return cReflexiveKeyword_1_0; }
		
		//end+="reflexive"
		public Assignment getEndAssignment_1_1() { return cEndAssignment_1_1; }
		
		//"reflexive"
		public Keyword getEndReflexiveKeyword_1_1_0() { return cEndReflexiveKeyword_1_1_0; }
	}
	public class TransitionPropertiesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.transitionProperties");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cColorKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cColorAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cColorCOLORTerminalRuleCall_0_1_0 = (RuleCall)cColorAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cThicknessKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cThicknessAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cThicknessFLOATTerminalRuleCall_1_1_0 = (RuleCall)cThicknessAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cCurvatureKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCurveAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCurveFLOATTerminalRuleCall_2_1_0 = (RuleCall)cCurveAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final RuleCall cDEFAULTTerminalRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final Assignment cPositionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPositionIDTerminalRuleCall_3_1_0 = (RuleCall)cPositionAssignment_3_1.eContents().get(0);
		
		//transitionProperties:
		//	"color" color+=COLOR
		//	| "thickness" thickness+=FLOAT
		//	| "curvature" curve+=FLOAT
		//	| DEFAULT position+=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//"color" color+=COLOR | "thickness" thickness+=FLOAT | "curvature" curve+=FLOAT | DEFAULT position+=ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"color" color+=COLOR
		public Group getGroup_0() { return cGroup_0; }
		
		//"color"
		public Keyword getColorKeyword_0_0() { return cColorKeyword_0_0; }
		
		//color+=COLOR
		public Assignment getColorAssignment_0_1() { return cColorAssignment_0_1; }
		
		//COLOR
		public RuleCall getColorCOLORTerminalRuleCall_0_1_0() { return cColorCOLORTerminalRuleCall_0_1_0; }
		
		//"thickness" thickness+=FLOAT
		public Group getGroup_1() { return cGroup_1; }
		
		//"thickness"
		public Keyword getThicknessKeyword_1_0() { return cThicknessKeyword_1_0; }
		
		//thickness+=FLOAT
		public Assignment getThicknessAssignment_1_1() { return cThicknessAssignment_1_1; }
		
		//FLOAT
		public RuleCall getThicknessFLOATTerminalRuleCall_1_1_0() { return cThicknessFLOATTerminalRuleCall_1_1_0; }
		
		//"curvature" curve+=FLOAT
		public Group getGroup_2() { return cGroup_2; }
		
		//"curvature"
		public Keyword getCurvatureKeyword_2_0() { return cCurvatureKeyword_2_0; }
		
		//curve+=FLOAT
		public Assignment getCurveAssignment_2_1() { return cCurveAssignment_2_1; }
		
		//FLOAT
		public RuleCall getCurveFLOATTerminalRuleCall_2_1_0() { return cCurveFLOATTerminalRuleCall_2_1_0; }
		
		//DEFAULT position+=ID
		public Group getGroup_3() { return cGroup_3; }
		
		//DEFAULT
		public RuleCall getDEFAULTTerminalRuleCall_3_0() { return cDEFAULTTerminalRuleCall_3_0; }
		
		//position+=ID
		public Assignment getPositionAssignment_3_1() { return cPositionAssignment_3_1; }
		
		//ID
		public RuleCall getPositionIDTerminalRuleCall_3_1_0() { return cPositionIDTerminalRuleCall_3_1_0; }
	}
	
	
	private final ModelElements pModel;
	private final ElementElements pElement;
	private final StateElements pState;
	private final StatesPropertiesElements pStatesProperties;
	private final TransitionElements pTransition;
	private final LabelElements pLabel;
	private final EndTransitionElements pEndTransition;
	private final TransitionPropertiesElements pTransitionProperties;
	private final TerminalRule tDEFAULT;
	private final TerminalRule tCOLOR;
	private final TerminalRule tFLOAT;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TSEGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pElement = new ElementElements();
		this.pState = new StateElements();
		this.pStatesProperties = new StatesPropertiesElements();
		this.pTransition = new TransitionElements();
		this.pLabel = new LabelElements();
		this.pEndTransition = new EndTransitionElements();
		this.pTransitionProperties = new TransitionPropertiesElements();
		this.tDEFAULT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.DEFAULT");
		this.tCOLOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.COLOR");
		this.tFLOAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fr.uha.ensisa.project.pan_chabalier.tse.TSE.FLOAT");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.uha.ensisa.project.pan_chabalier.tse.TSE".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	elements+=Element*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Element:
	//	states+=State
	//	| transitions+=Transition;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//State:
	//	"state" name+=ID statesPropriety+=StatesProperties*;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//StatesProperties:
	//	"color" color+=COLOR
	//	| "thickness" thickness+=FLOAT
	//	| "position" position+=ID
	//	| DEFAULT position+=ID;
	public StatesPropertiesElements getStatesPropertiesAccess() {
		return pStatesProperties;
	}
	
	public ParserRule getStatesPropertiesRule() {
		return getStatesPropertiesAccess().getRule();
	}
	
	//Transition:
	//	"transition" start+=ID end+=EndTransition proprietyStates+=transitionProperties* label=Label?
	//	| "initialTransition" init+=ID INT;
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//Label:
	//	"label" INT;
	public LabelElements getLabelAccess() {
		return pLabel;
	}
	
	public ParserRule getLabelRule() {
		return getLabelAccess().getRule();
	}
	
	//EndTransition:
	//	"->" end+=ID
	//	| "reflexive" end+="reflexive";
	public EndTransitionElements getEndTransitionAccess() {
		return pEndTransition;
	}
	
	public ParserRule getEndTransitionRule() {
		return getEndTransitionAccess().getRule();
	}
	
	//transitionProperties:
	//	"color" color+=COLOR
	//	| "thickness" thickness+=FLOAT
	//	| "curvature" curve+=FLOAT
	//	| DEFAULT position+=ID;
	public TransitionPropertiesElements getTransitionPropertiesAccess() {
		return pTransitionProperties;
	}
	
	public ParserRule getTransitionPropertiesRule() {
		return getTransitionPropertiesAccess().getRule();
	}
	
	//terminal DEFAULT:
	//	"DEFAULT" | "default";
	public TerminalRule getDEFAULTRule() {
		return tDEFAULT;
	}
	
	//terminal COLOR:
	//	"WHITE" | "BLACK" | "BLUE" | "CYAN" | "DARK_GRAY" | "GRAY" | "LIGHT_GRAY" | "GREEN" | "MAGENTA" | "ORANGE" | "PINK"
	//	| "RED" | "YELLOW";
	public TerminalRule getCOLORRule() {
		return tCOLOR;
	}
	
	//terminal FLOAT:
	//	INT '.' INT;
	public TerminalRule getFLOATRule() {
		return tFLOAT;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
