/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier;

import fr.uha.ensisa.project.pan_chabalier.TSEStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TSEStandaloneSetup extends TSEStandaloneSetupGenerated {
  public static void doSetup() {
    new TSEStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
