/*
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TSEStandaloneSetup extends TSEStandaloneSetupGenerated {

	def static void doSetup() {
		new TSEStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
