/*
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.validation

import fr.uha.ensisa.project.pan_chabalier.tse.tSE.CoordinatesStatesTransition
import fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TSEValidator extends AbstractTSEValidator {

//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					TSEPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
	boolean flag
	
	@Check
	def checkTransitionHaveExistingStates(CoordinatesStatesTransition statesTransitionName) {
		flag = false;
		TSEPackage.Literals.STATE__NAME.
		while(){
			if(.equals(statesTransitionName)){
			flag = true;
		}
		}
		
	 }
}
