/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse;

import fr.uha.ensisa.project.pan_chabalier.tse.AbstractTSERuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TSERuntimeModule extends AbstractTSERuntimeModule {
}
