/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.tSE;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Coordinates States Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.CoordinatesStatesTransition#getStateTransition <em>State Transition</em>}</li>
 * </ul>
 *
 * @see fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage#getCoordinatesStatesTransition()
 * @model
 * @generated
 */
public interface CoordinatesStatesTransition extends EObject
{
  /**
   * Returns the value of the '<em><b>State Transition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>State Transition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Transition</em>' attribute.
   * @see #setStateTransition(String)
   * @see fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage#getCoordinatesStatesTransition_StateTransition()
   * @model
   * @generated
   */
  String getStateTransition();

  /**
   * Sets the value of the '{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.CoordinatesStatesTransition#getStateTransition <em>State Transition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State Transition</em>' attribute.
   * @see #getStateTransition()
   * @generated
   */
  void setStateTransition(String value);

} // CoordinatesStatesTransition
