/**
 * generated by Xtext 2.12.0
 */
package fr.uha.ensisa.project.pan_chabalier.tse.tSE;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.TransitionProperties#getColor <em>Color</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.TransitionProperties#getThickness <em>Thickness</em>}</li>
 *   <li>{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.TransitionProperties#getCurve <em>Curve</em>}</li>
 * </ul>
 *
 * @see fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage#getTransitionProperties()
 * @model
 * @generated
 */
public interface TransitionProperties extends EObject
{
  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see #setColor(String)
   * @see fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage#getTransitionProperties_Color()
   * @model
   * @generated
   */
  String getColor();

  /**
   * Sets the value of the '{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.TransitionProperties#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see #getColor()
   * @generated
   */
  void setColor(String value);

  /**
   * Returns the value of the '<em><b>Thickness</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Thickness</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thickness</em>' attribute.
   * @see #setThickness(String)
   * @see fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage#getTransitionProperties_Thickness()
   * @model
   * @generated
   */
  String getThickness();

  /**
   * Sets the value of the '{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.TransitionProperties#getThickness <em>Thickness</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Thickness</em>' attribute.
   * @see #getThickness()
   * @generated
   */
  void setThickness(String value);

  /**
   * Returns the value of the '<em><b>Curve</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Curve</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Curve</em>' attribute.
   * @see #setCurve(String)
   * @see fr.uha.ensisa.project.pan_chabalier.tse.tSE.TSEPackage#getTransitionProperties_Curve()
   * @model
   * @generated
   */
  String getCurve();

  /**
   * Sets the value of the '{@link fr.uha.ensisa.project.pan_chabalier.tse.tSE.TransitionProperties#getCurve <em>Curve</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Curve</em>' attribute.
   * @see #getCurve()
   * @generated
   */
  void setCurve(String value);

} // TransitionProperties
